IF NOT EXISTS (SELECT 1 FROM information_schema.Routines WHERE ROUTINE_NAME = 'usp_User_Delete' AND ROUTINE_TYPE = 'PROCEDURE' AND ROUTINE_SCHEMA = 'dbo')
BEGIN
	EXEC('CREATE PROCEDURE usp_User_Delete as BEGIN SET NOCOUNT ON; END')
END
GO 

ALTER PROCEDURE usp_User_Delete
	@UserId int
AS
BEGIN
	DELETE FROM
		[User]
	WHERE
		UserId = @UserId
END
