IF NOT EXISTS (SELECT 1 FROM information_schema.Routines WHERE ROUTINE_NAME = 'usp_UserRole_GetList' AND ROUTINE_TYPE = 'PROCEDURE' AND ROUTINE_SCHEMA = 'dbo')
BEGIN
	EXEC('CREATE PROCEDURE usp_UserRole_GetList as BEGIN SET NOCOUNT ON; END')
END
GO 

ALTER PROCEDURE usp_UserRole_GetList
AS
BEGIN
	SELECT
		UserRoleId,
		Name
	FROM
		UserRole
END